### ISSUE TITLE
`_parse_driver': Unknown driver: synchrony

### ISSUE THREAD

**Issue by bmxpert1** [celluloid/celluloid-redis#12]
Is there a reason redis_ext.rb does not contain the synchrony driver like:

``` ruby
when "synchrony"
  require "redis/connection/synchrony"
  driver = Connection::Synchrony
```

Thanks!

**Comment by tarcieri** [comment]
Well, really this has been fixed upstream so this sort of method is no longer needed.

That said, I didn't include the synchrony driver to deter people from trying to use Celluloid and em-synchrony in the same program, which would be completely insane ;)

**Comment by bmxpert1** [comment]
Noob question: why would that be completely insane? I'm using a websocket server in rails which uses redis in em-synchrony fashion. Is combining celluloid and this going to cause issues?

**Comment by tarcieri** [comment]
Short answer: yes

**Comment by bmxpert1** [comment]
Alright thanks!
