### ISSUE TITLE
Dead lock on wait in the celluloid actor

### ISSUE THREAD

**Issue by k-solutions** [celluloid/celluloid-redis#3]
Following code fails with:

 D, [2013-03-24T17:04:42.494344 #6194] DEBUG -- : Terminating 4 actors...
D, [2013-03-24T17:04:42.495761 #6194] DEBUG -- : Shutdown completed cleanly
/home/hristo/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/thread.rb:71:in `sleep': deadlock detected (fatal)
    from /home/hristo/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/thread.rb:71:in`wait'
    from /home/hristo/Public/celluloid/lib/celluloid/mailbox.rb:67:in `receive'
    from /home/hristo/Public/celluloid/lib/celluloid/calls.rb:40:in`block in wait'
    from /home/hristo/Public/celluloid/lib/celluloid/calls.rb:39:in `loop'
    from /home/hristo/Public/celluloid/lib/celluloid/calls.rb:39:in`wait'
    from /home/hristo/Public/celluloid/lib/celluloid.rb:57:in `suspend'
    from /home/hristo/Public/celluloid/lib/celluloid/actor.rb:69:in`call'
    from /home/hristo/Public/celluloid/lib/celluloid/legacy.rb:14:in `method_missing'
    from examples/redis_pubsub.rb:35:in`<main>'

<pre>
#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
require 'celluloid/autostart'
require 'celluloid/redis'

# REDIS = Redis.new( :driver => :celluloid )
class RedisPubSub
  include Celluloid

  def initialize
    @@redis = ::Redis.new( :driver => :celluloid )
  end
  
  def send channel, message
    @@redis.publish channel, message
  end
  
  def run
    wait :terminate
  end
  
  def terminate
    signal :terminate
    super
  end
end

publisher = RedisPubSub.new
at_exit { publisher.terminate }

publisher.send 'test', 'test message'
publisher.run
</pre>

**Comment by tarcieri** [comment]
I'm thinking this deadlock is due to your use of signals. I don't understand what you're trying to accomplish with them.

That said I don't think this is a celluloid-redis or celluloid-related issue at all. If you want to block on the publisher actor, don't use signals, use `Celluloid.join(publisher)`

**Comment by k-solutions** [comment]
Thx for Celluloid.join but subscribe call is still blocking on next address to the actor

<pre>
#!/usr/bin/env ruby
require 'rubygems'
require 'bundler/setup'
require 'celluloid/autostart'
require 'celluloid/redis'
class RedisPubSub
  include Celluloid
  attr_reader :timer
  def initialize
    @redis = ::Redis.new( :driver => :celluloid )
    @timer  = every( 3.5 ) { puts "Hello from timer!" }
  end
  
  def ignate
    @timer.fire
  end
  
  def subscribe *channels #, message
    @redis.subscribe *channels do |on| # , 
      on.message { |channel,msg| puts msg }
    end 
  end
end
publisher = RedisPubSub.new
publisher.async.ignate
publisher.sleep 4
publisher.async.subscribe 'test' # , 'test message'
puts "Subscribed success!"
publisher.async.ignate
publisher.sleep 4
puts "Script ends"
</pre>

Output from this is 

<pre>
Hello from timer!
Hello from timer!
Subscribed success!
</pre>

and it stops there
